var graph = {
"nodes":[
{"name":"al-Ṣāliḥ Najm al-Dīn Ayyūb","date":"r. 637-647/1240-1249","Gender":"M","group":"Shajar"},
{"name":"Shajar al-Durr","date":"r. 648/1250","Gender":"F","group":"Shajar"},
{"name":"al-Muʿizz Aybak","date":"r. 648-655/1250-1257","Gender":"M","group":"Early Mamlūks"},
{"name":"al-Manṣūr ʿAlī","date":"r. 655-657/1257-1259","Gender":"M","group":"Early Mamlūks"},
{"name":"al-Muẓaffar Quṭuz","date":"r. 657-658/1259-1260","Gender":"M","group":"Early Mamlūks"},
{"name":"aẓ-Ẓāhir Baybars","date":"r. 658-676/1260-1277","Gender":"M","group":"Baybars"},
{"name":"as-Saʿīd Berka Khān","date":"r. 676-678/1277-1279","Gender":"M","group":"Sons of Baybars"},
{"name":"al-ʿĀdil Salamish","date":"r. 678/1279","Gender":"M","group":"Sons of Baybars"},
{"name":"al-Manṣūr Qalāwūn","date":"r. 678-689/1279-1290","Gender":"M","group":"Qalāwūn"},
{"name":"al-Ashraf Khalīl","date":"r. 689-693/1290-1293","Gender":"M","group":"Sons"},
{"name":"an-Nāṣir Muḥammad","date":"r. 693–694/1293–1294; 698–708/1299–1309; 709–741/1310-1341","Gender":"M","group":"Sons"},
{"name":"al-ʿĀdil Kitbughā","date":"r. 694-696/1294-1296","Gender":"M","group":"Manṣūrī Amirs"},
{"name":"al-Manṣūr Lājīn","date":"r. 696-698/1296-1298","Gender":"M","group":"Manṣūrī Amirs"},
{"name":"al-Muẓaffar Baybars al-Jāshankīr","date":"r. 708-709/1308-1310","Gender":"M","group":"Manṣūrī Amirs"},   
{"name":"al-Manṣūr Abū Bakr","date":"r. 741–742/1341","Gender":"M","group":"Grandsons"},
{"name":"al-Ashraf Kujuk","date":"r. 742/1341–1342","Gender":"M","group":"Grandsons"},
{"name":"an-Nāṣir Aḥmad","date":"r. 742–743/1342","Gender":"M","group":"Grandsons"},
{"name":"aṣ-Ṣāliḥ Ismāʿīl","date":"r. 743–746/1342–1345","Gender":"M","group":"Grandsons"},
{"name":"al-Kāmil Shaʿbān","date":"r. 746–747/1345–1346","Gender":"M","group":"Grandsons"},
{"name":"al-Muẓaffar Ḥājjī","date":"r. 747–748/1346–1347","Gender":"M","group":"Grandsons"},
{"name":"an-Nāṣir Ḥasan","date":"r. 748–752/1347–1351, 755–762/1354–1361","Gender":"M","group":"Grandsons"},
{"name":"aṣ-Ṣāliḥ Ṣāliḥ","date":"r. 752–755/1351–1354","Gender":"M","group":"Grandsons"},
{"name":"al-Manṣūr Muḥammad","date":"r. 762–764/1361–1363","Gender":"M","group":"Great Grandsons"},
{"name":"al-Ashraf Shaʿbān","date":"r. 764–778/1363–1377","Gender":"M","group":"Great Grandsons"},
{"name":"al-Manṣūr ʿAlī","date":"r. 778–783/1377–1381","Gender":"M","group":"Great Great Grandsons"},
{"name":"aṣ-Ṣāliḥ Ḥājjī","date":"r. 783–784/1381–1382, 791–792/1389–1390","Gender":"M","group":"Great Great Grandsons"},
{"name":"aẓ-Ẓāhir Barqūq","date":"r. 784-792/1382-1389 , 792-801/1390-1399","Gender":"M","group":"Other Amirs"},
{"name":"Relative of al-Ṣāliḥ Najm al-Dīn Ayyūb","date":"d. unknown","Gender":"F","group":"Ayyubid"},
{"name":"Bint aẓ-Ẓāhir Baybars","date":"d. unknown","Gender":"F","group":"Baybars' son"},
{"name":"Relative of al-Manṣūr Lājīn","date":"d. unknown","Gender":"F","group":"Awlād al-Nās"},
{"name":"Shaktāy","date":"","Gender":"M","group":"Non-Mamlūks"},
{"name":"Ashlun bint Shaktāy","date":"d. unknown","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Zawjat Qalāwūn","date":"","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Umm aṣ-Ṣāliḥ","date":"d. 683/1284","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"aṣ-Ṣāliḥ ʿAlī","date":"d. 1288","Gender":"M","group":"Qalāwūnid Princes & Princesses"},
{"name":"Mankabay b. Nughāy","date":"","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Mūsá","date":"d. 718/1318-9","Gender":"M","group":"Qalāwūnid Princes & Princesses"},
{"name":"Ardūkin b. Nughāy","date":"d. 724/1324","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Khātūn","date":"d. before 689/1290","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Nughāy","date":"","Gender":"M","group":"Non-Mamlūks"},
{"name":"Salār","date":"d. 710/1310","Gender":"M","group":"Manṣūrī amir"},
{"name":"Bint Salār","date":"","Gender":"F","group":"Awlād al-Nās"},
{"name":"Ṭughāy","date":"d. 749/1348-9","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Ṭulunbāy bint Ṭughāy","date":"d. 741/1340","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Manklībughā al-Silāḥdār","date":"d. 731/1330","Gender":"M","group":"Nāṣirī Amirs"},
{"name":"ʿUmar ibn Arghūn al-Nāṣirī al-Nāʾib","date":"d. Unknown","Gender":"M","group":"Awlād al-Nās"},
{"name":"Arghūn al-Nāṣirī al-Nāʾib","date":"","Gender":"M","group":"Nāṣirī amīr"},
{"name":"Abū Bakr ibn Arghūn al-Nāṣirī al-Nāʾib","date":"","Gender":"M","group":"Awlād al-Nās"},
{"name":"Ṣūṣūn","date":"d. 734/1334","Gender":"M","group":"Other Amirs"},
{"name":"Qawṣūn","date":"d. 742/1342","Gender":"M","group":"Nāṣirī amīr"},
{"name":"Ukht Qawṣūn","date":"","Gender":"F","group":"Awlād al-Nās"},
{"name":"Khalīl ibn Qawṣūn","date":"d. 778/1376","Gender":"M","group":"Awlād al-Nās"},
{"name":"Bint al-Malik al-Nāṣir Muḥammad 1","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Bint al-Malik al-Nāṣir Muḥammad 2","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Bint al-Malik al-Nāṣir Muḥammad 3","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Bint al-Malik al-Nāṣir Muḥammad 4","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Bint al-Malik al-Nāṣir Muḥammad 5","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Bint al-Malik al-Nāṣir Muḥammad 6","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Bint al-Malik al-Nāṣir Muḥammad 7","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Zawjat al-Malik al-Nāsir Muḥammad 1","date":"d. after 747/1346","Gender":"F","group":"Qalāwūnid Royal Wives"},  
{"name":"Zawjat al-Malik al-Nāsir Muḥammad 2","date":"d. Unknown","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Zawjat al-Malik al-Nāsir Muḥammad 3","date":"d. Unknown","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Bayāḍ","date":"d. 731/1330-1","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Narjis","date":"d. after 756/1356","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Kudā","date":"","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Ḥusayn","date":"d. 764/1363","Gender":"M","group":"Qalāwūnid Princes & Princesses"},
{"name":"Arghūn al-ʿAlāʾī","date":"","Gender":"M","group":"Nāṣirī amīr"},
{"name":"Lājīn al-ʿAlāʾī","date":"","Gender":"M","group":"Other Amirs"},
{"name":"Shaykhū","date":"","Gender":"M","group":"Nāṣirī (Ḥasan) Amirs"},
{"name":"Qumārī","date":"","Gender":"M","group":"Other Amirs"},
{"name":"Ānūk ibn al-Malik al-Nāṣir Muḥammad","date":"d. 741/1340","Gender":"M","group":"Qalāwūnīd prince"},
{"name":"Bint Baktamur al-Sāqī","date":"","Gender":"F","group":"Awlād al-Nās"},
{"name":"Baktamur al-Sāqī","date":"","Gender":"M","group":"Nāṣirī amīr"},
{"name":"Aḥmad ibn Baktamur al-Sāqī","date":"d. 733/1332","Gender":"M","group":"Awlād al-Nās"},
{"name":"Quṭlūmalik bint Tankiz al-Ḥusāmī","date":"d. after 755/1354","Gender":"F","group":"Awlād al-Nās"},
{"name":"Tankiz al-Ḥusāmī","date":"d. 741/1341","Gender":"M","group":"Nāṣirī amīr"},
{"name":"Aḥmad ibn Tankiz al-Ḥusāmī","date":"","Gender":"M","group":"Awlād al-Nās"},
{"name":"Muḥammad ibn Tankiz al-Ḥusāmī","date":"","Gender":"M","group":"Awlād al-Nās"},
{"name":"Ṭāẓ","date":"","Gender":"M","group":"Nāṣirī (Ḥasan) Amirs"},
{"name":"Bint Ṭāẓ","date":"","Gender":"F","group":"Awlād al-Nās"},
{"name":"Ṭuquzdamur al-Ḥamawī","date":"d. 746/1345","Gender":"M","group":"Other Amirs"},
{"name":"Bint Ṭuquzdamur al-Ḥamawī 1","date":"","Gender":"F","group":"Awlād al-Nās"},
{"name":"Maliktamur al-Sarjuwānī","date":"","Gender":"M","group":"Other Amirs"},
{"name":"Ṭāyirbughā","date":"d. 738/1337","Gender":"M","group":"Other Amirs"},
{"name":"Bint Ṭāyirbughā 1","date":"","Gender":"F","group":"Awlād al-Nās"},
{"name":"Arghūn al-Ismāʿīlī","date":"d. Unknown","Gender":"M","group":"Other Amirs"},
{"name":"Yūsuf","date":"d. 747/1346","Gender":"M","group":"Qalāwūnid Princes & Princesses"},
{"name":"Bint Jankalī ibn al-Bābā","date":"","Gender":"F","group":"Awlād al-Nās"},
{"name":"Jankalī ibn al-Bābā","date":"","Gender":"F","group":"Manṣūrī Amirs"},
{"name":"Ittifāq","date":"","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Zawjat al-Ṣāliḥ Ismāʿīl 1","date":"","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Bint al-Ṣāliḥ Ismāʿīl","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Bint al-Malik al-Nāṣir Muḥammad 9","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Zahrāʾ","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Kaydā","date":"","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"al-Sitt Ḥadaq","date":"","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Ṭūlūbiyya bint ʿAbd Allāh al-Nāṣiriyya","date":"","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Ibn Yalbughā al-ʿUmarī al-Nāṣirī","date":"","Gender":"M","group":"Awlād al-Nās"},
{"name":"Yalbughā al-ʿUmarī al-Nāṣirī","date":"","Gender":"M","group":"Nāṣirī (Ḥasan) Amirs"},
{"name":"Aḥmad","date":"","Gender":"M","group":"Qalāwūnid Princes & Princesses"},
{"name":"Bint al-Malik al-Nāṣir Ḥasan 1","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Shaqrāʾ","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Urūs","date":"","Gender":"M","group":"Other Amirs"},
{"name":"Tatar al-Ḥijāziyyah","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Sayf al-dīn Ṭughāytamur al-ʿUmarī al-Nāṣirī","date":"","Gender":"M","group":"Other Amirs"},
{"name":"Maliktamur al-Ḥijāzī","date":"","Gender":"M","group":"Other Amirs"},
{"name":"Tankizbughā","date":"","Gender":"M","group":"Other Amirs"},
{"name":"Bint Tankizbughā","date":"","Gender":"F","group":"Awlād al-Nās"},
{"name":"Bint al-Malik al-Nāṣir Muḥammad 8","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Tankizbughā al-Māridānī","date":"","Gender":"M","group":"Other Amirs"},
{"name":"Ardū","date":"","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Ibrāhīm","date":"","Gender":"M","group":"Qalāwūnid Princes & Princesses"},
{"name":"Bint Ṭuquzdamur al-Ḥamawī 2","date":"","Gender":"F","group":"Awlād al-Nās"},
{"name":"Ḥūṭūn Khātūn","date":"","Gender":"F","group":"Awlād al-Nās"},
{"name":"Jankalī ibn al-Bābā","date":"","Gender":"M","group":"Manṣūrī Amirs"},
{"name":"Bint Ṭāyirbugha 2","date":"","Gender":"F","group":"Awlād al-Nās"},
{"name":"Baraka","date":"","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Uljāy al-Yūsūfī","date":"","Gender":"M","group":"Nāṣirī (Ḥasan) amir"},
{"name":"Qāsim al-Bashtakī","date":"","Gender":"M","group":"Other Amirs"},
{"name":"Ānaṣ","date":"d. 783/1382","Gender":"M","group":"Non-Mamlūks"},
{"name":"Bint Ṭughāytamur al-Niẓāmī","date":"","Gender":"F","group":"Awlād al-Nās"},
{"name":"Ṭughāytamur al-Niẓāmī","date":"","Gender":"M","group":"Other Amirs"},
{"name":"Khawand bint Manklībughā","date":"","Gender":"F","group":"Awlād al-Nās"},
{"name":"Manklībughā","date":"","Gender":"M","group":"Other Amirs"},
{"name":"Sāra","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Fāṭima","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Zawjat al-Ashraf Shaʿbān 1","date":"","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Bint al-Malik al-Ashraf Shaʿbān 2","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Yalbughā al-Aḥmadī al-Majnūn","date":"","Gender":"M","group":"Other Amirs"},
{"name":"Hājar","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Khadīja","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Zawjat al-Malik al-Ashraf Shaʿbān 2","date":"","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Ṣalāḥ al-dīn Muḥammad ibn Muḥammad ibn Tankiz al-Ḥusāmī","date":"","Gender":"M","group":"Awlād al-Nās"},
{"name":"Āqbughā ʿAbd al-Wāḥid al-Nāṣirī","date":"","Gender":"M","group":"Other Amirs"},
{"name":"Bint Aḥmad","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Aḥmad","date":"d. 783/1381","Gender":"M","group":"Qalāwūnid Princes & Princesses"},
{"name":"Bint al-Malik al-Ashraf Shaʿbān 1","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Minṭāsh","date":"","Gender":"M","group":"Other Amirs"},
{"name":"ʿĀʾisha al-Qurdumiyya","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Qurdum al-Nāṣirī al-Ḥamawī","date":"","Gender":"M","group":"Other Amirs"},
{"name":"Bint aẓ-Ẓāhir Baybars","date":"","Gender":"F","group":"Sons of Baybars"},
{"name":"Daughter of Byzantine Emperor","date":"","Gender":"F","group":"Non-Mamlūks"},
{"name":"Bint al-ʿĀdil Kitbughā","date":"","Gender":"F","group":"Awlād al-Nās"},
{"name":"Baydarā al-ʿĀdilī","date":"","Gender":"M","group":"Other Amirs"},
{"name":"Zawjat Ṭuquzdamur al-Ḥamawī","date":"","Gender":"F","group":"Awlād al-Nās"},
{"name":"Baygharā","date":"","Gender":"M","group":"Other Amirs"},
{"name":"Bahādur al-Damurdāshī","date":"","Gender":"M","group":"Other Amirs"},
{"name":"Āqsunqur al-Nāṣirī","date":"","Gender":"M","group":"Nāṣirī Amirs"},
{"name":"Yaḥya ibn Ṭāyirbughā","date":"","Gender":"M","group":"Awlād al-Nās"},
{"name":"Zakariyyā ibn Ṭāyirbughā","date":"","Gender":"M","group":"Awlād al-Nās"},
{"name":"ʿAlī","date":"d. 783/1381","Gender":"M","group":"Qalāwūnid Princes & Princesses"},
{"name":"Abū Bakr","date":"d. 803/1400","Gender":"M","group":"Qalāwūnid Princes & Princesses"},    
{"name":"Aḥmad","date":"d. before 783/1381","Gender":"M","group":"Qalāwūnid Princes & Princesses"},
{"name":"Ramaḍān","date":"d. before 783/1381","Gender":"M","group":"Qalāwūnid Princes & Princesses"},    
{"name":"Qāsim","date":"d. before 783/1381","Gender":"M","group":"Qalāwūnid Princes & Princesses"},
{"name":"Muḥammad","date":"d. before 783/1381","Gender":"M","group":"Qalāwūnid Princes & Princesses"},
{"name":"Ismāʿīl","date":"d. 797/1395","Gender":"M","group":"Qalāwūnid Princes & Princesses"},
{"name":"al-Malik al-Manṣūr Ānūk","date":"d. 793/1390-1","Gender":"M","group":"Qalāwūnid Princes & Princesses"},
{"name":"Jānibak","date":"d. 831/1428","Gender":"M","group":"Qalāwūnid Princes & Princesses"},
{"name":"Aḥmad","date":"d. Unknown","Gender":"M","group":"Qalāwūnid Princes & Princesses"},
{"name":"Ibrāhīm","date":"d. Unknown","Gender":"M","group":"Qalāwūnid Princes & Princesses"},
{"name":"Qāsim","date":"d. Unknown","Gender":"M","group":"Qalāwūnid Princes & Princesses"},
{"name":"Ibrāhīm","date":"d. 783/1381","Gender":"M","group":"Qalāwūnid Princes & Princesses"},
{"name":"Bint Tankiz al-Ḥusāmī 2","date":"d. Unknown","Gender":"F","group":"Awlād al-Nās"},
{"name":"ʿĀʾisha","date":"d. Unknown","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"ʿIzz al-dīn Ṭuqṭāy","date":"d. Unknown","Gender":"M","group":"Other Amirs"}    
],
"links": [ 
{"source": 1, "target": 0, "value": 1},
{"source": 2, "target": 1, "value": 2}, 
{"source": 3, "target": 2, "value": 2},
{"source": 5, "target": 27, "value": 2},
{"source": 6, "target": 5, "value": 2},
{"source": 7, "target": 5, "value": 2}, 
{"source": 9, "target": 8, "value": 3},
{"source": 10, "target": 8, "value": 3},
{"source": 12, "target": 28, "value": 2},
{"source": 13, "target": 29, "value": 2},
{"source": 14, "target": 10, "value": 2},
{"source": 15, "target": 10, "value": 2}, 
{"source": 15, "target": 110, "value": 2},
{"source": 16, "target": 10, "value": 2},
{"source": 17, "target": 10, "value": 2},
{"source": 18, "target": 10, "value": 2},
{"source": 19, "target": 10, "value": 2},
{"source": 20, "target": 10, "value": 2},
{"source": 21, "target": 10, "value": 2},
{"source": 22, "target": 19, "value": 2},
{"source": 23, "target": 65, "value": 2},
{"source": 23, "target": 116, "value": 2},
{"source": 24, "target": 23, "value": 2},
{"source": 25, "target": 23, "value": 2},
{"source": 26, "target": 129, "value": 2},
{"source": 27, "target": 0, "value": 2},
{"source": 28, "target": 5, "value": 2},
{"source": 29, "target": 12, "value": 2},
{"source": 30, "target": 31, "value": 2},
{"source": 31, "target": 8, "value": 2},
{"source": 32, "target": 8, "value": 2},
{"source": 33, "target": 8, "value": 2},
{"source": 34, "target": 8, "value": 2},
{"source": 34, "target": 33, "value": 2},
{"source": 35, "target": 11, "value": 2},
{"source": 35, "target": 34, "value": 2},
{"source": 36, "target": 34, "value": 2},
{"source": 36, "target": 35, "value": 2},    
{"source": 37, "target": 9, "value": 2},
{"source": 37, "target": 10, "value": 2},
{"source": 38, "target": 6, "value": 2},    
{"source": 38, "target": 8, "value": 2},
{"source": 38, "target": 33, "value": 2},
{"source": 39, "target": 35, "value": 2},
{"source": 39, "target": 37, "value": 2},
{"source": 40, "target": 41, "value": 2},
{"source": 41, "target": 36, "value": 2},
{"source": 42, "target": 10, "value": 2},
{"source": 43, "target": 10, "value": 2},
{"source": 44, "target": 43, "value": 2},
{"source": 45, "target": 43, "value": 2},
{"source": 46, "target": 35, "value": 2},
{"source": 46, "target": 47, "value": 2},
{"source": 47, "target": 52, "value": 2},
{"source": 48, "target": 43, "value": 2},
{"source": 49, "target": 48, "value": 2},
{"source": 49, "target": 50, "value": 2},
{"source": 49, "target": 53, "value": 2},
{"source": 50, "target": 10, "value": 2},
{"source": 51, "target": 49, "value": 2},
{"source": 51, "target": 53, "value": 2},
{"source": 52, "target": 10, "value": 2},
{"source": 52, "target": 58, "value": 2},
{"source": 53, "target": 10, "value": 2},
{"source": 53, "target": 58, "value": 2},
{"source": 54, "target": 10, "value": 2},
{"source": 54, "target": 58, "value": 2},
{"source": 55, "target": 10, "value": 2},
{"source": 55, "target": 58, "value": 2},
{"source": 56, "target": 10, "value": 2},
{"source": 56, "target": 58, "value": 2},
{"source": 57, "target": 10, "value": 2},
{"source": 57, "target": 58, "value": 2},
{"source": 58, "target": 10, "value": 2},
{"source": 58, "target": 58, "value": 2},
{"source": 59, "target": 10, "value": 2},
{"source": 60, "target": 10, "value": 2},
{"source": 61, "target": 10, "value": 2},
{"source": 62, "target": 10, "value": 2},
{"source": 63, "target": 10, "value": 2},
{"source": 64, "target": 10, "value": 2}, 
{"source": 65, "target": 10, "value": 2},
{"source": 65, "target": 58, "value": 2},
{"source": 66, "target": 59, "value": 2}, 
{"source": 67, "target": 60, "value": 2},
{"source": 68, "target": 53, "value": 2},
{"source": 69, "target": 54, "value": 2},
{"source": 70, "target": 10, "value": 2},
{"source": 70, "target": 42, "value": 2},  
{"source": 71, "target": 14, "value": 2}, 
{"source": 71, "target": 17, "value": 2}, 
{"source": 72, "target": 18, "value": 2},
{"source": 72, "target": 70, "value": 2},
{"source": 72, "target": 71, "value": 2},
{"source": 72, "target": 73, "value": 2},
{"source": 72, "target": 74, "value": 2}, 
{"source": 73, "target": 74, "value": 2},  
{"source": 74, "target": 10, "value": 2},
{"source": 75, "target": 73, "value": 2}, 
{"source": 75, "target": 76, "value": 2},
{"source": 75, "target": 77, "value": 2},
{"source": 76, "target": 56, "value": 2},
{"source": 77, "target": 55, "value": 2},
{"source": 78, "target": 57, "value": 2},
{"source": 78, "target": 79, "value": 2},
{"source": 79, "target": 65, "value": 2}, 
{"source": 80, "target": 58, "value": 2},
{"source": 80, "target": 63, "value": 2},
{"source": 81, "target": 14, "value": 2},
{"source": 81, "target": 17, "value": 2},
{"source": 81, "target": 18, "value": 2},
{"source": 81, "target": 80, "value": 2},
{"source": 81, "target": 144, "value": 2}, 
{"source": 82, "target": 62, "value": 2},
{"source": 83, "target": 84, "value": 2},
{"source": 84, "target": 16, "value": 2},
{"source": 85, "target": 63, "value": 2},
{"source": 86, "target": 10, "value": 2},
{"source": 86, "target": 63, "value": 2},
{"source": 87, "target": 86, "value": 2},
{"source": 88, "target": 87, "value": 2},
{"source": 89, "target": 17, "value": 2},
{"source": 89, "target": 18, "value": 2},
{"source": 89, "target": 19, "value": 2},
{"source": 90, "target": 17, "value": 2},
{"source": 91, "target": 17, "value": 2}, 
{"source": 91, "target": 90, "value": 2},
{"source": 91, "target": 145, "value": 2},
{"source": 92, "target": 10, "value": 2},
{"source": 92, "target": 59, "value": 2},
{"source": 93, "target": 10, "value": 2},
{"source": 93, "target": 59, "value": 2},
{"source": 94, "target": 19, "value": 2},
{"source": 95, "target": 20, "value": 2},
{"source": 96, "target": 20, "value": 2},
{"source": 96, "target": 98, "value": 2},    
{"source": 97, "target": 96, "value": 2},
{"source": 97, "target": 98, "value": 2},
{"source": 99, "target": 20, "value": 2},
{"source": 99, "target": 96, "value": 2},
{"source": 100, "target": 20, "value": 2},
{"source": 100, "target": 23, "value": 2},
{"source": 100, "target": 96, "value": 2},
{"source": 101, "target": 20, "value": 2},
{"source": 101, "target": 96, "value": 2},
{"source": 102, "target": 101, "value": 2},
{"source": 103, "target": 10, "value": 2},
{"source": 103, "target": 64, "value": 2},
{"source": 104, "target": 103, "value": 2},
{"source": 105, "target": 103, "value": 2},
{"source": 106, "target": 103, "value": 2},
{"source": 107, "target": 23, "value": 2},
{"source": 107, "target": 103, "value": 2},
{"source": 107, "target": 106, "value": 2},
{"source": 108, "target": 10, "value": 2},
{"source": 108, "target": 64, "value": 2},
{"source": 109, "target": 108, "value": 2},
{"source": 110, "target": 10, "value": 2},
{"source": 110, "target": 18, "value": 2},
{"source": 110, "target": 147, "value": 2},
{"source": 111, "target": 10, "value": 2},
{"source": 111, "target": 61, "value": 2},
{"source": 112, "target": 63, "value": 2},
{"source": 112, "target": 80, "value": 2},
{"source": 112, "target": 111, "value": 2},
{"source": 113, "target": 111, "value": 2},
{"source": 114, "target": 113, "value": 2},
{"source": 115, "target": 83, "value": 2},
{"source": 115, "target": 111, "value": 2},
{"source": 116, "target": 65, "value": 2},
{"source": 116, "target": 117, "value": 2},
{"source": 118, "target": 130, "value": 2},
{"source": 119, "target": 26, "value": 2},
{"source": 120, "target": 23, "value": 2},
{"source": 121, "target": 120, "value": 2},
{"source": 122, "target": 23, "value": 2},
{"source": 123, "target": 122, "value": 2},
{"source": 123, "target": 124, "value": 2},
{"source": 123, "target": 125, "value": 2},
{"source": 124, "target": 65, "value": 2},
{"source": 124, "target": 116, "value": 2},
{"source": 125, "target": 23, "value": 2},
{"source": 125, "target": 126, "value": 2},
{"source": 126, "target": 23, "value": 2},
{"source": 127, "target": 23, "value": 2},
{"source": 127, "target": 126, "value": 2},
{"source": 128, "target": 127, "value": 2},
{"source": 129, "target": 123, "value": 2},
{"source": 129, "target": 125, "value": 2},
{"source": 130, "target": 23, "value": 2},
{"source": 130, "target": 122, "value": 2},
{"source": 131, "target": 23, "value": 2},
{"source": 131, "target": 132, "value": 2},
{"source": 132, "target": 77, "value": 2},
{"source": 133, "target": 42, "value": 2},
{"source": 134, "target": 25, "value": 2},
{"source": 134, "target": 135, "value": 2},
{"source": 135, "target": 19, "value": 2},
{"source": 135, "target": 163, "value": 2},
{"source": 136, "target": 23, "value": 2},
{"source": 136, "target": 131, "value": 2},
{"source": 137, "target": 136, "value": 2},
{"source": 138, "target": 10, "value": 2},
{"source": 138, "target": 61, "value": 2},
{"source": 139, "target": 138, "value": 2},
{"source": 140, "target": 12, "value": 2},
{"source": 141, "target": 12, "value": 2},
{"source": 142, "target": 11, "value": 2},
{"source": 143, "target": 142, "value": 2},
{"source": 144, "target": 80, "value": 2},
{"source": 144, "target": 112, "value": 2},
{"source": 145, "target": 91, "value": 2},
{"source": 146, "target": 92, "value": 2},
{"source": 147, "target": 93, "value": 2},
{"source": 148, "target": 83, "value": 2},
{"source": 149, "target": 83, "value": 2},
{"source": 150, "target": 23, "value": 2},
{"source": 150, "target": 122, "value": 2},
{"source": 151, "target": 23, "value": 2},
{"source": 151, "target": 122, "value": 2},
{"source": 152, "target": 23, "value": 2},
{"source": 152, "target": 126, "value": 2},
{"source": 153, "target": 23, "value": 2},
{"source": 153, "target": 126, "value": 2},
{"source": 154, "target": 23, "value": 2},
{"source": 154, "target": 126, "value": 2},
{"source": 155, "target": 23, "value": 2},
{"source": 155, "target": 126, "value": 2},
{"source": 156, "target": 23, "value": 2},
{"source": 156, "target": 126, "value": 2},
{"source": 157, "target": 65, "value": 2},
{"source": 157, "target": 116, "value": 2},
{"source": 158, "target": 65, "value": 2},
{"source": 158, "target": 116, "value": 2},
{"source": 159, "target": 65, "value": 2},
{"source": 159, "target": 116, "value": 2}, 
{"source": 160, "target": 65, "value": 2},
{"source": 160, "target": 116, "value": 2}, 
{"source": 161, "target": 10, "value": 2},
{"source": 161, "target": 43, "value": 2},
{"source": 162, "target": 10, "value": 2},
{"source": 162, "target": 43, "value": 2},
{"source": 163, "target": 18, "value": 2},
{"source": 163, "target": 19, "value": 2},
{"source": 163, "target": 75, "value": 2},
{"source": 164, "target": 18, "value": 2},
{"source": 164, "target": 163, "value": 2},
{"source": 165, "target": 164, "value": 2}    
]
}    
